### ISSUE TITLE
Error with 'chord' plot

### ISSUE THREAD

**Issue by TomSmithCGAT** [ococrook/bandle#12]
With `plotTranslocations(bandleres, type='chord')`, I get `Error in dev.off() : cannot shut down device 1 (the null device)`.

I can make it run using `dev.set(dev.next())` first.

Is the following line needed? https://github.com/ococrook/bandle/blob/141c9b0cb929676db867be719d02ba791e5075d0/R/bandle-plots.R#L288

If so, should it be this instead? `while (!is.null(dev.list()))  dev.off()`

**Comment by lmsimp** [comment]
Thanks very much @TomSmithCGAT will check this now
