### ISSUE TITLE
vignette

### ISSUE THREAD

**Issue by ococrook** [ococrook/bandle#3]
First vignette done. Other vignettes to follow
- convergence
- more interesting plots (waiting for Lisa)
- MRmethod
- GAM based methods

**Comment by ococrook** [comment]
expand vignette to include more of an introduciton

**Comment by lmsimp** [comment]
Vignette update: Currently, I can not get the `plotTranslocations` function with `type = chord` to render in the `html` in the vignette. No problems visualising this in R though... I need to do some investigating. One option is to upload a static figure/screenshot of the chord plot if it won't render in the html? Also, would be nice to show the summary table in the vignette - need to add this too.

**Comment by ococrook** [comment]
Thanks, these should be straightforward to add I think

**Comment by lmsimp** [comment]
>Also, would be nice to show the summary table in the vignette - need to add this too.

**Comment by lmsimp** [comment]
>Also, would be nice to show the summary table in the vignette - need to add this too.
This can be done with 
```r
plotTranslocations(params, table = TRUE)
```

**Comment by ococrook** [comment]
did you send a pull request?
