### ISSUE TITLE
Condition 2 - outlier issue 

### ISSUE THREAD

**Issue by JosieAC** [ococrook/bandle#6]
https://github.com/ococrook/bandle/blob/cdada3118820cb437e60063327a48433ae26e860/R/bandle-function.R#L317

Causes outlier values to be between 0 and 2.

**Comment by ococrook** [comment]
thanks @JosieAC, fixed the the recent version. Can you confirm it works for you and then close the issue?

**Comment by JosieAC** [comment]
Yep, all good now.
