### ISSUE TITLE
mcmc_plot_probs error

### ISSUE THREAD

**Issue by JosieAC** [ococrook/bandle#7]
The `mcmc_plot_probs` gives following error:

```
Warning messages:
1: In depth(vp) : reached elapsed time limit
2: Computation failed in `stat_ydensity()`:
'weights' must all be finite 
```

Think line 38-39 is the issue - comma and bracket in wrong place(?):
https://github.com/ococrook/bandle/blob/c727b343af955565f9153533fd31248bcb05ccb3/R/bandle-plots.R#L38

The below edit seems to work for me (where params = bandleres, fname = "Q14147") :

```
ch <- chains(bandleres)[[1]]
dfr <- as.data.frame(ch@nicheProb[[1]]["Q14147", , ])
dfr_long <- data.frame(Organelle = rep(names(dfr), each = nrow(dfr)),
                       Probability = unlist(dfr, use.names = FALSE),
                       row.names = NULL,
                       stringsAsFactors = FALSE)
gg2 <- ggplot(dfr_long,
              aes(Organelle, Probability),
                  width = Probability) +
  geom_violin(aes(fill = Organelle), scale = "width", bw = 0.5)
gg2 <- gg2 + theme_bw() +
  scale_fill_manual(values = pRoloc::getStockcol()[seq_len(nrow(dfr))]) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        axis.title.x = element_blank())
gg2 <- gg2 +
  ylab("Membership Probability") +
  ggtitle(paste0("Distribution of Subcellular Membership for Protein ", "Q14147" ))
gg2 <- gg2 +
  theme(legend.position = "none")
gg2
```

**Comment by ococrook** [comment]
thanks Josie, I'll have a play tomorrow and update!

**Comment by JosieAC** [comment]
Thank you! 👍

**Comment by JosieAC** [comment]
Just an additional comment on this function (possibly just personal preference though) - the text is quite small. Have used the following which seems like a nice size (also rotated labels to fit):

```
gg2 <- gg2 + theme_bw() +
  scale_fill_manual(values = pRoloc::getStockcol()[seq_len(nrow(dfr))]) +
  theme(text = element_text(size=15), axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank())
```

**Comment by ococrook** [comment]
cheers! I have a look at a few options and see what works but if it's a good default then I'll go with that :)

**Comment by ococrook** [comment]
@JosieAC Should work now! sorry for the delay. I agree with the text size change they are much better. Careful not to set `bw = 0.5` this big as it will distor the violins. I suggest about somwhere between 0.05 to 0.1 is usually good, maybe higher if its quite lumpy.

**Comment by ococrook** [comment]
Could you close the issue when you've check it works for you?

**Comment by JosieAC** [comment]
Hi Olly,

Sorry I've been off the end of this week. I'll check this today.

**Comment by JosieAC** [comment]
![image](https://user-images.githubusercontent.com/49618410/116118165-f20a0880-a6b4-11eb-93f1-069cb89cb8c7.png)

Works fine now, thank you :)
